# -*- coding: utf-8 -*-
"""Census_income.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VXz9ZnEt6yEurTWGHjT3jmGtMUEoTTkr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

!unzip "/content/archive (1).zip"

df = pd.read_csv("/content/archive (1).zip")

df

df.head(3)

df.tail()

df.shape

print("Number of Rowa-->",df.shape[0])
print("Number of Colums-->",df.shape[1])

df.drop_duplicates()

df

df.isna()

df.isna().sum()

df.isna().sum().sum()

df.describe()

df.info()

df["age"].mean()

df["age"].max()

df["age"].min()

df_object = df.select_dtypes("object")

df_object

import seaborn as sns

sns.countplot(df_object['workclass'])

plt.figure(figsize=(10,7))
sns.countplot(df_object, x="workclass")
plt.xticks(rotation=90)

df_object.columns

plt.figure(figsize=(18,30))
for i in range(len(df_object.columns)):
  plt.subplot(5,2,i+2)
  sns.countplot(df_object[df_object.columns[i]])
  plt.title(f"Countplote of {df_object.columns[i]}")
  plt.xticks(rotation=90)
  plt.tight_layout()

df_int = df.select_dtypes(exclude="object")

df_int

sns.distplot(df_int["age"])

df_int.columns

plt.figure(figsize=(18,30))
for i in range(len(df_int.columns)):
  plt.subplot(5,2,i+1)
  sns.distplot(df_int[df_int.columns[i]])
  plt.title(f"Distplot of {df_int.columns}")
  plt.xticks(rotation=90)
  plt.tight_layout()

df

sns.stripplot(x=df['income'],y=df['age'])

sns.stripplot(x=df['income'],y=df['education'])

